/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BagRouteImport } from './routes/bag'
import { Route as AskAuraRouteImport } from './routes/ask-aura'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonsIndexRouteImport } from './routes/salons.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as SalonsSlugRouteImport } from './routes/salons.$slug'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MarketplaceCategoryRouteImport } from './routes/marketplace.$category'
import { Route as JournalCategoryRouteImport } from './routes/journal.$category'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AskAuraConversationIdRouteImport } from './routes/ask-aura.$conversationId'
import { Route as SalonsServiceServiceRouteImport } from './routes/salons.service.$service'
import { Route as SalonsAreaAreaRouteImport } from './routes/salons.area.$area'
import { Route as MarketplaceProductSlugRouteImport } from './routes/marketplace.product.$slug'
import { Route as JournalArticleSlugRouteImport } from './routes/journal.article.$slug'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAuraRoute = AskAuraRouteImport.update({
  id: '/ask-aura',
  path: '/ask-aura',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIndexRoute = SalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsSlugRoute = SalonsSlugRouteImport.update({
  id: '/salons/$slug',
  path: '/salons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCategoryRoute = MarketplaceCategoryRouteImport.update({
  id: '/marketplace/$category',
  path: '/marketplace/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCategoryRoute = JournalCategoryRouteImport.update({
  id: '/journal/$category',
  path: '/journal/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAuraConversationIdRoute = AskAuraConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AskAuraRoute,
} as any)
const SalonsServiceServiceRoute = SalonsServiceServiceRouteImport.update({
  id: '/salons/service/$service',
  path: '/salons/service/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsAreaAreaRoute = SalonsAreaAreaRouteImport.update({
  id: '/salons/area/$area',
  path: '/salons/area/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductSlugRoute = MarketplaceProductSlugRouteImport.update({
  id: '/marketplace/product/$slug',
  path: '/marketplace/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalArticleSlugRoute = JournalArticleSlugRouteImport.update({
  id: '/journal/article/$slug',
  path: '/journal/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/ask-aura': typeof AskAuraRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/ask-aura/$conversationId': typeof AskAuraConversationIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$category': typeof JournalCategoryRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/salons/': typeof SalonsIndexRoute
  '/journal/article/$slug': typeof JournalArticleSlugRoute
  '/marketplace/product/$slug': typeof MarketplaceProductSlugRoute
  '/salons/area/$area': typeof SalonsAreaAreaRoute
  '/salons/service/$service': typeof SalonsServiceServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/ask-aura': typeof AskAuraRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/ask-aura/$conversationId': typeof AskAuraConversationIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$category': typeof JournalCategoryRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/journal': typeof JournalIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/salons': typeof SalonsIndexRoute
  '/journal/article/$slug': typeof JournalArticleSlugRoute
  '/marketplace/product/$slug': typeof MarketplaceProductSlugRoute
  '/salons/area/$area': typeof SalonsAreaAreaRoute
  '/salons/service/$service': typeof SalonsServiceServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/ask-aura': typeof AskAuraRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/ask-aura/$conversationId': typeof AskAuraConversationIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$category': typeof JournalCategoryRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/salons/': typeof SalonsIndexRoute
  '/journal/article/$slug': typeof JournalArticleSlugRoute
  '/marketplace/product/$slug': typeof MarketplaceProductSlugRoute
  '/salons/area/$area': typeof SalonsAreaAreaRoute
  '/salons/service/$service': typeof SalonsServiceServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/ask-aura'
    | '/bag'
    | '/checkout'
    | '/profile'
    | '/recommendations'
    | '/ask-aura/$conversationId'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$category'
    | '/marketplace/$category'
    | '/orders/$orderId'
    | '/salons/$slug'
    | '/journal/'
    | '/marketplace/'
    | '/orders/'
    | '/salons/'
    | '/journal/article/$slug'
    | '/marketplace/product/$slug'
    | '/salons/area/$area'
    | '/salons/service/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/ask-aura'
    | '/bag'
    | '/checkout'
    | '/profile'
    | '/recommendations'
    | '/ask-aura/$conversationId'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$category'
    | '/marketplace/$category'
    | '/orders/$orderId'
    | '/salons/$slug'
    | '/journal'
    | '/marketplace'
    | '/orders'
    | '/salons'
    | '/journal/article/$slug'
    | '/marketplace/product/$slug'
    | '/salons/area/$area'
    | '/salons/service/$service'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/ask-aura'
    | '/bag'
    | '/checkout'
    | '/profile'
    | '/recommendations'
    | '/ask-aura/$conversationId'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$category'
    | '/marketplace/$category'
    | '/orders/$orderId'
    | '/salons/$slug'
    | '/journal/'
    | '/marketplace/'
    | '/orders/'
    | '/salons/'
    | '/journal/article/$slug'
    | '/marketplace/product/$slug'
    | '/salons/area/$area'
    | '/salons/service/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AskAuraRoute: typeof AskAuraRouteWithChildren
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  JournalCategoryRoute: typeof JournalCategoryRoute
  MarketplaceCategoryRoute: typeof MarketplaceCategoryRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  SalonsSlugRoute: typeof SalonsSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SalonsIndexRoute: typeof SalonsIndexRoute
  JournalArticleSlugRoute: typeof JournalArticleSlugRoute
  MarketplaceProductSlugRoute: typeof MarketplaceProductSlugRoute
  SalonsAreaAreaRoute: typeof SalonsAreaAreaRoute
  SalonsServiceServiceRoute: typeof SalonsServiceServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-aura': {
      id: '/ask-aura'
      path: '/ask-aura'
      fullPath: '/ask-aura'
      preLoaderRoute: typeof AskAuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/': {
      id: '/salons/'
      path: '/salons'
      fullPath: '/salons/'
      preLoaderRoute: typeof SalonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$slug': {
      id: '/salons/$slug'
      path: '/salons/$slug'
      fullPath: '/salons/$slug'
      preLoaderRoute: typeof SalonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$category': {
      id: '/marketplace/$category'
      path: '/marketplace/$category'
      fullPath: '/marketplace/$category'
      preLoaderRoute: typeof MarketplaceCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$category': {
      id: '/journal/$category'
      path: '/journal/$category'
      fullPath: '/journal/$category'
      preLoaderRoute: typeof JournalCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-aura/$conversationId': {
      id: '/ask-aura/$conversationId'
      path: '/$conversationId'
      fullPath: '/ask-aura/$conversationId'
      preLoaderRoute: typeof AskAuraConversationIdRouteImport
      parentRoute: typeof AskAuraRoute
    }
    '/salons/service/$service': {
      id: '/salons/service/$service'
      path: '/salons/service/$service'
      fullPath: '/salons/service/$service'
      preLoaderRoute: typeof SalonsServiceServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/area/$area': {
      id: '/salons/area/$area'
      path: '/salons/area/$area'
      fullPath: '/salons/area/$area'
      preLoaderRoute: typeof SalonsAreaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/product/$slug': {
      id: '/marketplace/product/$slug'
      path: '/marketplace/product/$slug'
      fullPath: '/marketplace/product/$slug'
      preLoaderRoute: typeof MarketplaceProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/article/$slug': {
      id: '/journal/article/$slug'
      path: '/journal/article/$slug'
      fullPath: '/journal/article/$slug'
      preLoaderRoute: typeof JournalArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AskAuraRouteChildren {
  AskAuraConversationIdRoute: typeof AskAuraConversationIdRoute
}

const AskAuraRouteChildren: AskAuraRouteChildren = {
  AskAuraConversationIdRoute: AskAuraConversationIdRoute,
}

const AskAuraRouteWithChildren =
  AskAuraRoute._addFileChildren(AskAuraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  AskAuraRoute: AskAuraRouteWithChildren,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  JournalCategoryRoute: JournalCategoryRoute,
  MarketplaceCategoryRoute: MarketplaceCategoryRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  SalonsSlugRoute: SalonsSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SalonsIndexRoute: SalonsIndexRoute,
  JournalArticleSlugRoute: JournalArticleSlugRoute,
  MarketplaceProductSlugRoute: MarketplaceProductSlugRoute,
  SalonsAreaAreaRoute: SalonsAreaAreaRoute,
  SalonsServiceServiceRoute: SalonsServiceServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
